version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: polybanque-dev
    container_name: polybanque-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
    command: bin/rails server -b 0.0.0.0
    stdin_open: true
    tty: true

