services:
  web:
    image: ruby:3.4.5
    container_name: polybanque-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      RAILS_ENV: development
    working_dir: /app
    entrypoint: /app/bin/docker-entrypoint.dev
    command: bundle exec rails server -b 0.0.0.0
    tty: true
    stdin_open: true

volumes:
  bundle_cache: